

my_list = [
{:address=>"ottpscfbgoiyfri[iwzhojzrpzuinumuwd]orfroqlcemumqbqqrea", :supernet_sequences=>"ottpscfbgoiyfriorfroqlcemumqbqqrea", :aba=>"mum", :hypernet_sequences=>["iwzhojzrpzuinumuwd"], :bab=>"umu", :supports_ssl=>true}, 
{:address=>"nesmourutitzqtolwd[rurfefjvljejcufm]jagkqdwpkefkjdz[cctohikipqxxbdjxsg]badmffkslhmgsxqscf", :supernet_sequences=>"nesmourutitzqtolwdbadmffkslhmgsxqscf", :aba=>"uru", :hypernet_sequences=>["rurfefjvljejcufm"], :bab=>"rur", :supports_ssl=>true}, 
{:address=>"zmnirrxetiwyese[cedxmaoadgjjvsesk]nuisspyclmncqlasmuy[zxwlwmbzbjmvubgcf]hfqniztoirmsdwz[zlffqhttbpehxoabzhx]upmydjqzzwefvgdpqu", :supernet_sequences=>"zmnirrxetiwyeseupmydjqzzwefvgdpqu", :aba=>"ese", :hypernet_sequences=>["cedxmaoadgjjvsesk"], :bab=>"ses", :supports_ssl=>true}, 
{:address=>"ejgpdxesfyoyaggmymi[axfkdoyoqkpkhusfwe]pnczsmszqevkqiwlfc[dqhzcqjzpgnoknmv]ldrjdhopfyctlqtn", :supernet_sequences=>"ejgpdxesfyoyaggmymildrjdhopfyctlqtn", :aba=>"yoy", :hypernet_sequences=>["axfkdoyoqkpkhusfwe"], :bab=>"oyo", :supports_ssl=>true}, 
{:address=>"gvmytvlyluvnmemhgjr[bvqbhytqwpyemefwo]sygljhpvyjnuxzjqy", :supernet_sequences=>"gvmytvlyluvnmemhgjrsygljhpvyjnuxzjqy", :aba=>"mem", :hypernet_sequences=>["bvqbhytqwpyemefwo"], :bab=>"eme", :supports_ssl=>true}, 
{:address=>"zootaoveazcrmtbda[qlxlwntntbkjtkqve]vffdsbekufzemgwomh[vzllvqlmloffyyldfh]alltnttrzqrchacoiqm", :supernet_sequences=>"zootaoveazcrmtbdaalltnttrzqrchacoiqm", :aba=>"tnt", :hypernet_sequences=>["qlxlwntntbkjtkqve"], :bab=>"ntn", :supports_ssl=>true}, 
{:address=>"hbeghglpgqnwpxqio[pcujpvhzhghnyjkmppe]jwcnwmqwctqgoxpj", :supernet_sequences=>"hbeghglpgqnwpxqiojwcnwmqwctqgoxpj", :aba=>"ghg", :hypernet_sequences=>["pcujpvhzhghnyjkmppe"], :bab=>"hgh", :supports_ssl=>true}, 
{:address=>"apqmhkpxrtrfwulqbq[trthojavkcrlcgc]oikizlfqpukeudv[afgmhbusoqjubra]ajbuhxzuhecopcxm[lowqlmwiyvmdojjla]jrrhjmopywkqrhlgicl", :supernet_sequences=>"apqmhkpxrtrfwulqbqjrrhjmopywkqrhlgicl", :aba=>"rtr", :hypernet_sequences=>["trthojavkcrlcgc"], :bab=>"trt", :supports_ssl=>true}, 
{:address=>"mvjlhovwivdanexv[iaphahshtwtnhoeoqsk]syolycabjeiwtwtec", :supernet_sequences=>"mvjlhovwivdanexvsyolycabjeiwtwtec", :aba=>"wtw", :hypernet_sequences=>["iaphahshtwtnhoeoqsk"], :bab=>"twt", :supports_ssl=>true}, 
{:address=>"xwcoczwpeprblqvdsze[fcqzupldpqdpibi]peaetflnafpkrqz[aibobqkhvfzpwaajxj]mzlrkrfslubibbu", :supernet_sequences=>"xwcoczwpeprblqvdszemzlrkrfslubibbu", :aba=>"bib", :hypernet_sequences=>["fcqzupldpqdpibi"], :bab=>"ibi", :supports_ssl=>true}, 
{:address=>"nvouetegmutetgw[keqvyocxdetebkcgl]qfhnyfdnjqnklpad[swuvsfhrnzsnatb]zjwqmrmphlgwdnms[hdlfprihcbcemfn]lrraefojxvtpxljil", :supernet_sequences=>"nvouetegmutetgwlrraefojxvtpxljil", :aba=>"tet", :hypernet_sequences=>["keqvyocxdetebkcgl"], :bab=>"ete", :supports_ssl=>true}, 
{:address=>"rezxczwcihbkywyq[sdzzflizzygfiovwyw]jhtiwvelkbaqhvnylca[xpnwnmqbaawlyqz]kftcwdejxaznztqsbhy", :supernet_sequences=>"rezxczwcihbkywyqkftcwdejxaznztqsbhy", :aba=>"ywy", :hypernet_sequences=>["sdzzflizzygfiovwyw"], :bab=>"wyw", :supports_ssl=>true}, 
{:address=>"hizeoqbkkesksvtjotj[wkvmcgctdzwhzlubt]aegcgfmdneprdbw", :supernet_sequences=>"hizeoqbkkesksvtjotjaegcgfmdneprdbw", :aba=>"gcg", :hypernet_sequences=>["wkvmcgctdzwhzlubt"], :bab=>"cgc", :supports_ssl=>true}, 
{:address=>"vphviazdmmvtcyc[dcomcirqycymvqkm]meeikjmqliqraeqd", :supernet_sequences=>"vphviazdmmvtcycmeeikjmqliqraeqd", :aba=>"cyc", :hypernet_sequences=>["dcomcirqycymvqkm"], :bab=>"ycy", :supports_ssl=>true}, 
{:address=>"kjgjcnoipwnlqnk[hpukxdqokakrgjgjpk]nvinvznddzuhupepemb", :supernet_sequences=>"kjgjcnoipwnlqnknvinvznddzuhupepemb", :aba=>"jgj", :hypernet_sequences=>["hpukxdqokakrgjgjpk"], :bab=>"gjg", :supports_ssl=>true}, 
{:address=>"mywakayudrxzofpri[qlywfoydoqmsmaoygp]xpwmtcqqfqsmsys", :supernet_sequences=>"mywakayudrxzofprixpwmtcqqfqsmsys", :aba=>"sms", :hypernet_sequences=>["qlywfoydoqmsmaoygp"], :bab=>"msm", :supports_ssl=>true}, 
{:address=>"ztncnhqvomvfnkhca[ohbigcgrevrnpvuwgpv]lnjucgcpghvtzlrgkh", :supernet_sequences=>"ztncnhqvomvfnkhcalnjucgcpghvtzlrgkh", :aba=>"cgc", :hypernet_sequences=>["ohbigcgrevrnpvuwgpv"], :bab=>"gcg", :supports_ssl=>true}, 
{:address=>"cqnuuhyddzalcxc[fjmqzkljrqjbexcxxf]pbjsvyixepnkthndhb[xztvuzlknucygyvegxp]nwxzswdvaspdufotcxs[bivsecxgawosnflmfd]bvdtxxionieorvecr", :supernet_sequences=>"cqnuuhyddzalcxcbvdtxxionieorvecr", :aba=>"cxc", :hypernet_sequences=>["fjmqzkljrqjbexcxxf"], :bab=>"xcx", :supports_ssl=>true}, 
{:address=>"txqpvnrfxykothvao[uikgxsmnyxwlobod]tddprkiwjtdcwbobzrn", :supernet_sequences=>"txqpvnrfxykothvaotddprkiwjtdcwbobzrn", :aba=>"bob", :hypernet_sequences=>["uikgxsmnyxwlobod"], :bab=>"obo", :supports_ssl=>true}, 
{:address=>"cjmaltrbirusgyoirp[eipxzkuhukkdcdh]iqyymukrkwitywb[dcvtitgqvetxqip]sldydwlrcdcrljhzu", :supernet_sequences=>"cjmaltrbirusgyoirpsldydwlrcdcrljhzu", :aba=>"cdc", :hypernet_sequences=>["eipxzkuhukkdcdh"], :bab=>"dcd", :supports_ssl=>true}, 
{:address=>"wiuprpjfojcowmy[vmrpruwhtzbwyciid]ntbkrodejcrwavjfqfa", :supernet_sequences=>"wiuprpjfojcowmyntbkrodejcrwavjfqfa", :aba=>"prp", :hypernet_sequences=>["vmrpruwhtzbwyciid"], :bab=>"rpr", :supports_ssl=>true}, 
{:address=>"rfqbvdzxrnrbuhvw[wzurtnrnslhoqkdoaja]vuxsxofemkrjzqkk", :supernet_sequences=>"rfqbvdzxrnrbuhvwvuxsxofemkrjzqkk", :aba=>"rnr", :hypernet_sequences=>["wzurtnrnslhoqkdoaja"], :bab=>"nrn", :supports_ssl=>true}, 
{:address=>"pbbcmecbydtmjigfn[giiambqbdgbgntq]zaaqvlpkysxuvbgbo", :supernet_sequences=>"pbbcmecbydtmjigfnzaaqvlpkysxuvbgbo", :aba=>"bgb", :hypernet_sequences=>["giiambqbdgbgntq"], :bab=>"gbg", :supports_ssl=>true}, 
{:address=>"ltlddqcbkkayshw[qdedbdppzuqdhfaxt]doedeeehsibaylpsnk", :supernet_sequences=>"ltlddqcbkkayshwdoedeeehsibaylpsnk", :aba=>"ede", :hypernet_sequences=>["qdedbdppzuqdhfaxt"], :bab=>"ded", :supports_ssl=>true}, 
{:address=>"xtnewbseisluqott[ukktnadfrptzmvmnmwe]nfevmvifmaaubdrytcb", :supernet_sequences=>"xtnewbseisluqottnfevmvifmaaubdrytcb", :aba=>"vmv", :hypernet_sequences=>["ukktnadfrptzmvmnmwe"], :bab=>"mvm", :supports_ssl=>true}, 
{:address=>"djblesvduxlxfxp[grmuswjaheivlqvtst]yrqstsaryoqejwkd", :supernet_sequences=>"djblesvduxlxfxpyrqstsaryoqejwkd", :aba=>"sts", :hypernet_sequences=>["grmuswjaheivlqvtst"], :bab=>"tst", :supports_ssl=>true}, 
{:address=>"kpyoqmyglnrmxculu[tuyuqjronsgluls]whuymvpcdxvxrimvmow", :supernet_sequences=>"kpyoqmyglnrmxculuwhuymvpcdxvxrimvmow", :aba=>"ulu", :hypernet_sequences=>["tuyuqjronsgluls"], :bab=>"lul", :supports_ssl=>true}, 
{:address=>"rvfdfyaemhgyeynw[hmmkdfdhadrqkxzzmsj]ugfozgghllznjhdxw[ucrgusuuqthlgxx]ipiercifxtkghbkf", :supernet_sequences=>"rvfdfyaemhgyeynwipiercifxtkghbkf", :aba=>"fdf", :hypernet_sequences=>["hmmkdfdhadrqkxzzmsj"], :bab=>"dfd", :supports_ssl=>true}, 
{:address=>"zkcihebtrfmiryqkd[ybedpynfafkkrbfdm]ovrsmnhexyqblafad", :supernet_sequences=>"zkcihebtrfmiryqkdovrsmnhexyqblafad", :aba=>"afa", :hypernet_sequences=>["ybedpynfafkkrbfdm"], :bab=>"faf", :supports_ssl=>true}, 
{:address=>"elgbshsnykhiyndouao[nhumkawagmrztsamd]fwqupmyuogneywsyhub[zzcemywfdswhvjpl]ockclifwawqsyzt", :supernet_sequences=>"elgbshsnykhiyndouaoockclifwawqsyzt", :aba=>"waw", :hypernet_sequences=>["nhumkawagmrztsamd"], :bab=>"awa", :supports_ssl=>true}, 
{:address=>"oiksidcbtzhhtnegqa[vdxnacjfxbcsjzqdq]ixvwmdqdaleuzjniki", :supernet_sequences=>"oiksidcbtzhhtnegqaixvwmdqdaleuzjniki", :aba=>"dqd", :hypernet_sequences=>["vdxnacjfxbcsjzqdq"], :bab=>"qdq", :supports_ssl=>true}, 
{:address=>"ljywtdshrtzqzrln[lqzqgywtrpgszaigfv]vjyyvrbkjdiiminfas", :supernet_sequences=>"ljywtdshrtzqzrlnvjyyvrbkjdiiminfas", :aba=>"zqz", :hypernet_sequences=>["lqzqgywtrpgszaigfv"], :bab=>"qzq", :supports_ssl=>true}, 
{:address=>"jbdmjeyxyksaonmswm[vhxyxtashfdrzjzytoq]jpkbmclxjtprrhmaz", :supernet_sequences=>"jbdmjeyxyksaonmswmjpkbmclxjtprrhmaz", :aba=>"yxy", :hypernet_sequences=>["vhxyxtashfdrzjzytoq"], :bab=>"xyx", :supports_ssl=>true}, 
{:address=>"qgpylzwwdjxmepsc[bumaitztsvayatapvl]gotathwcrjrsknrfuk", :supernet_sequences=>"qgpylzwwdjxmepscgotathwcrjrsknrfuk", :aba=>"tat", :hypernet_sequences=>["bumaitztsvayatapvl"], :bab=>"ata", :supports_ssl=>true}, 
{:address=>"kqbwgctrhxwrkkedau[occltggonhshykttsrr]snshslgqtlgejanlg", :supernet_sequences=>"kqbwgctrhxwrkkedausnshslgqtlgejanlg", :aba=>"shs", :hypernet_sequences=>["occltggonhshykttsrr"], :bab=>"hsh", :supports_ssl=>true}, 
{:address=>"hwjwuhdokecprunbju[jhftguwujsuetdriyu]vcgpesthcnwuwpwes", :supernet_sequences=>"hwjwuhdokecprunbjuvcgpesthcnwuwpwes", :aba=>"wuw", :hypernet_sequences=>["jhftguwujsuetdriyu"], :bab=>"uwu", :supports_ssl=>true}, 
{:address=>"hcqlfxoahajthjesrdy[nammwfgfdqnjewunwz]pdzecgfgatymrrntt", :supernet_sequences=>"hcqlfxoahajthjesrdypdzecgfgatymrrntt", :aba=>"gfg", :hypernet_sequences=>["nammwfgfdqnjewunwz"], :bab=>"fgf", :supports_ssl=>true}, 
{:address=>"sanarwdtnkaemdsoj[ojswyaadxpnpzcm]acjrepbjwnnpncdf", :supernet_sequences=>"sanarwdtnkaemdsojacjrepbjwnnpncdf", :aba=>"npn", :hypernet_sequences=>["ojswyaadxpnpzcm"], :bab=>"pnp", :supports_ssl=>true}, 
{:address=>"tmdniznfpsrdaivxpcp[nlebmzzfjfklqixhk]sbusrwexlbpswiyslbh[tuvimwrkchmarbvl]ykhoceojfjugoim", :supernet_sequences=>"tmdniznfpsrdaivxpcpykhoceojfjugoim", :aba=>"jfj", :hypernet_sequences=>["nlebmzzfjfklqixhk"], :bab=>"fjf", :supports_ssl=>true}, 
{:address=>"wmwfxoaocwtzuhvenl[yzpbmaoazbchjxozl]oulzkybjweqqzml[ydkamvkncxomqsibme]fcuomzdfejvijxeniaf", :supernet_sequences=>"wmwfxoaocwtzuhvenlfcuomzdfejvijxeniaf", :aba=>"oao", :hypernet_sequences=>["yzpbmaoazbchjxozl"], :bab=>"aoa", :supports_ssl=>true}, 
{:address=>"clyxvevuyzylpdud[jmwhfhkzrzzkawp]nwcvtlwlwnbebgdz[cbnfsolnppgafml]mxhbrzrialopbbk", :supernet_sequences=>"clyxvevuyzylpdudmxhbrzrialopbbk", :aba=>"rzr", :hypernet_sequences=>["jmwhfhkzrzzkawp"], :bab=>"zrz", :supports_ssl=>true}, 
{:address=>"hiekvarctkixnmypau[dafmuxavuaosooos]czvsosvafizsjiouwi", :supernet_sequences=>"hiekvarctkixnmypauczvsosvafizsjiouwi", :aba=>"sos", :hypernet_sequences=>["dafmuxavuaosooos"], :bab=>"oso", :supports_ssl=>true}, 
{:address=>"dcdcoboftwhtitlto[qdqpbbobdncixqwhmn]cdjrukqmcdbzwji", :supernet_sequences=>"dcdcoboftwhtitltocdjrukqmcdbzwji", :aba=>"obo", :hypernet_sequences=>["qdqpbbobdncixqwhmn"], :bab=>"bob", :supports_ssl=>true}, 
{:address=>"maeefdbswszxotz[sdfwswrwotoblvzk]bqmhwlxmzvjnorn[phhhipunsmqfmormtk]aasvyeqeffypmcop", :supernet_sequences=>"maeefdbswszxotzaasvyeqeffypmcop", :aba=>"sws", :hypernet_sequences=>["sdfwswrwotoblvzk"], :bab=>"wsw", :supports_ssl=>true}, 
{:address=>"honratmzckbtooiwan[epebkioukueaexbb]xyakukoiqfmtdhvxf", :supernet_sequences=>"honratmzckbtooiwanxyakukoiqfmtdhvxf", :aba=>"kuk", :hypernet_sequences=>["epebkioukueaexbb"], :bab=>"uku", :supports_ssl=>true}, 
{:address=>"jqajvhvbrkrynxg[yekfvwkborakrkfl]bovxzhceonjclmgecgy", :supernet_sequences=>"jqajvhvbrkrynxgbovxzhceonjclmgecgy", :aba=>"rkr", :hypernet_sequences=>["yekfvwkborakrkfl"], :bab=>"krk", :supports_ssl=>true}, 
{:address=>"jzhfwqxoqsgnrnex[ccrtrnroigtbvrnjeji]bbhfsodufjqhjvplii[mcubmtdgwttmmnazhpt]hovifldmlnbzrwqicaz", :supernet_sequences=>"jzhfwqxoqsgnrnexhovifldmlnbzrwqicaz", :aba=>"nrn", :hypernet_sequences=>["ccrtrnroigtbvrnjeji"], :bab=>"rnr", :supports_ssl=>true}, 
{:address=>"roximfsrbnzyzjmn[bqugwcdliqyzyaqiupv]rpdidncsfgexyncbg[amzmtmqwzipkjfy]fqnscfsjmxjlpoccvfd[bpebfxoinyaqsgjpb]dykidfsbcykdobqe", :supernet_sequences=>"roximfsrbnzyzjmndykidfsbcykdobqe", :aba=>"zyz", :hypernet_sequences=>["bqugwcdliqyzyaqiupv"], :bab=>"yzy", :supports_ssl=>true}, 
{:address=>"phuncbfvyiwxfour[oauntpjxaqvwvqn]liffvpoxrbljogpcwvw", :supernet_sequences=>"phuncbfvyiwxfourliffvpoxrbljogpcwvw", :aba=>"wvw", :hypernet_sequences=>["oauntpjxaqvwvqn"], :bab=>"vwv", :supports_ssl=>true}, 
{:address=>"augjtgfyoatluixgc[atdsbsouunywohfnk]dpghgakdvfscbapsm[nkodybopavlbeikalqj]myhpkcbsbkbjfgj", :supernet_sequences=>"augjtgfyoatluixgcmyhpkcbsbkbjfgj", :aba=>"bsb", :hypernet_sequences=>["atdsbsouunywohfnk"], :bab=>"sbs", :supports_ssl=>true}, 
{:address=>"exzcpmjdjiagpvsvin[aontczoixbznfwsvss]hdlmrrdtbumlfvril[gcuizdwjbzyhttw]apadljkbcsylwgekv", :supernet_sequences=>"exzcpmjdjiagpvsvinapadljkbcsylwgekv", :aba=>"vsv", :hypernet_sequences=>["aontczoixbznfwsvss"], :bab=>"svs", :supports_ssl=>true}, 
{:address=>"ctautcpnnufupce[qtydhgcjjqofrfay]lfahmjfjyppehyp[qzaxqkpopvwzqofe]rkcqkjpgptshvoucer[qmczzorygyrwbxiji]zljzfavjmwawfrfr", :supernet_sequences=>"ctautcpnnufupcezljzfavjmwawfrfr", :aba=>"rfr", :hypernet_sequences=>["qtydhgcjjqofrfay"], :bab=>"frf", :supports_ssl=>true}, 
{:address=>"bjgdyrlrhtkbqrjohwj[gcmcelqjvjadxqnj]tlupekhzidsrscrf[oqadjqqatohbjwxrneo]ykhccsunlyamcmmk", :supernet_sequences=>"bjgdyrlrhtkbqrjohwjykhccsunlyamcmmk", :aba=>"mcm", :hypernet_sequences=>["gcmcelqjvjadxqnj"], :bab=>"cmc", :supports_ssl=>true}, 
{:address=>"mhwhttcwzcntsbufi[afretswhwxhwkptb]srrajfoeahmhecarmu[wgjragqlbpfbfpd]epytkbjxmblfnkwhlhe", :supernet_sequences=>"mhwhttcwzcntsbufiepytkbjxmblfnkwhlhe", :aba=>"hwh", :hypernet_sequences=>["afretswhwxhwkptb"], :bab=>"whw", :supports_ssl=>true}, 
{:address=>"xfoshshomwdgssxla[uhshvhbfofuhdsqk]zbzynuiyfagqpemuplr", :supernet_sequences=>"xfoshshomwdgssxlazbzynuiyfagqpemuplr", :aba=>"shs", :hypernet_sequences=>["uhshvhbfofuhdsqk"], :bab=>"hsh", :supports_ssl=>true}, 
{:address=>"lympkckqyhgbaumc[oodkeqjyhckceptyqui]ejkkqbitfscazcx", :supernet_sequences=>"lympkckqyhgbaumcejkkqbitfscazcx", :aba=>"kck", :hypernet_sequences=>["oodkeqjyhckceptyqui"], :bab=>"ckc", :supports_ssl=>true}, 
{:address=>"tllvdxtvmesnmauwk[qaomhmguwvmsjbwrwz]gvzyhjymfhmheexe", :supernet_sequences=>"tllvdxtvmesnmauwkgvzyhjymfhmheexe", :aba=>"hmh", :hypernet_sequences=>["qaomhmguwvmsjbwrwz"], :bab=>"mhm", :supports_ssl=>true}, 
{:address=>"acajjiclnscuxdsyxv[axykpgkepnjhrhfgqvr]slbbdyluiqetchbrhrm", :supernet_sequences=>"acajjiclnscuxdsyxvslbbdyluiqetchbrhrm", :aba=>"rhr", :hypernet_sequences=>["axykpgkepnjhrhfgqvr"], :bab=>"hrh", :supports_ssl=>true}, 
{:address=>"fzfcqlltfzjujqeym[jeaiiecptdpgfsfccuc]sfsekysmcjtdxjc", :supernet_sequences=>"fzfcqlltfzjujqeymsfsekysmcjtdxjc", :aba=>"sfs", :hypernet_sequences=>["jeaiiecptdpgfsfccuc"], :bab=>"fsf", :supports_ssl=>true}, 
{:address=>"apdywyijusgxzfj[sgbhrwbwywwisyg]ssiiosnfconncgiy", :supernet_sequences=>"apdywyijusgxzfjssiiosnfconncgiy", :aba=>"ywy", :hypernet_sequences=>["sgbhrwbwywwisyg"], :bab=>"wyw", :supports_ssl=>true}, 
{:address=>"vbjenrifdqsyzlwga[wmjenjnqufhqohvgc]uhrzouilmqjnjigwpa", :supernet_sequences=>"vbjenrifdqsyzlwgauhrzouilmqjnjigwpa", :aba=>"jnj", :hypernet_sequences=>["wmjenjnqufhqohvgc"], :bab=>"njn", :supports_ssl=>true}, 
{:address=>"udumujkujngtkcfv[klinhdudyghspdsga]gxavvcsxqxvaziqrmsm[htseffbehxafyhoars]ghilivgeuuzjlmih[vtjpcrmvldjluqdazun]mebwzbxywmrfhet", :supernet_sequences=>"udumujkujngtkcfvmebwzbxywmrfhet", :aba=>"udu", :hypernet_sequences=>["klinhdudyghspdsga"], :bab=>"dud", :supports_ssl=>true}, 
{:address=>"nobwzchgrycgkxc[tqoxhzxeorivdtdkde]ctdtkwzsvuxfgjtjg", :supernet_sequences=>"nobwzchgrycgkxcctdtkwzsvuxfgjtjg", :aba=>"tdt", :hypernet_sequences=>["tqoxhzxeorivdtdkde"], :bab=>"dtd", :supports_ssl=>true}, 
{:address=>"oxjkoqahhqqcxcoxksg[bouywtiajyfmanxcx]xgqpjxtkaejvmqckkuf", :supernet_sequences=>"oxjkoqahhqqcxcoxksgxgqpjxtkaejvmqckkuf", :aba=>"cxc", :hypernet_sequences=>["bouywtiajyfmanxcx"], :bab=>"xcx", :supports_ssl=>true}, 
{:address=>"rjrldatkdhvzvgcux[iuhectextisybzvz]vycerefkzhnmdyg", :supernet_sequences=>"rjrldatkdhvzvgcuxvycerefkzhnmdyg", :aba=>"vzv", :hypernet_sequences=>["iuhectextisybzvz"], :bab=>"zvz", :supports_ssl=>true}, 
{:address=>"omuyrkrubieiduzegr[gcigoszvylmdrlrc]jtlrlsgqxiqtciehh", :supernet_sequences=>"omuyrkrubieiduzegrjtlrlsgqxiqtciehh", :aba=>"lrl", :hypernet_sequences=>["gcigoszvylmdrlrc"], :bab=>"rlr", :supports_ssl=>true}, 
{:address=>"gdbeqewbrhyfbfpeti[yvyiclmkwzelbqi]sktocytuvyvpcia", :supernet_sequences=>"gdbeqewbrhyfbfpetisktocytuvyvpcia", :aba=>"vyv", :hypernet_sequences=>["yvyiclmkwzelbqi"], :bab=>"yvy", :supports_ssl=>true}, 
{:address=>"tdwoqxlhhaqkdmv[cxayaazioswycmwj]pkenayaygxyrtqrqugi", :supernet_sequences=>"tdwoqxlhhaqkdmvpkenayaygxyrtqrqugi", :aba=>"yay", :hypernet_sequences=>["cxayaazioswycmwj"], :bab=>"aya", :supports_ssl=>true}, 
{:address=>"nvflxkucsnbsltnp[iqhnmiyolnoxjzjzjvl]ctdsnjzjaflstsy", :supernet_sequences=>"nvflxkucsnbsltnpctdsnjzjaflstsy", :aba=>"jzj", :hypernet_sequences=>["iqhnmiyolnoxjzjzjvl"], :bab=>"zjz", :supports_ssl=>true}, 
{:address=>"glmwwqvembkbsnvs[skbkkvnoycklltrnyrd]irlewhaeagdiojbr", :supernet_sequences=>"glmwwqvembkbsnvsirlewhaeagdiojbr", :aba=>"bkb", :hypernet_sequences=>["skbkkvnoycklltrnyrd"], :bab=>"kbk", :supports_ssl=>true}, 
{:address=>"yxjwddyrzrzhqrarheo[dcayrrmkvazrzzlpqh]gkvbwuimfochtndis", :supernet_sequences=>"yxjwddyrzrzhqrarheogkvbwuimfochtndis", :aba=>"rzr", :hypernet_sequences=>["dcayrrmkvazrzzlpqh"], :bab=>"zrz", :supports_ssl=>true}, 
{:address=>"ubsustsojocdyjv[obkxihfxtkbaeusurk]zmlqtgokothiokq", :supernet_sequences=>"ubsustsojocdyjvzmlqtgokothiokq", :aba=>"sus", :hypernet_sequences=>["obkxihfxtkbaeusurk"], :bab=>"usu", :supports_ssl=>true}, 
{:address=>"peqyzkuviznbwojhtys[svfilvdawzpmtygynd]fpfggygzketpcrrqx", :supernet_sequences=>"peqyzkuviznbwojhtysfpfggygzketpcrrqx", :aba=>"gyg", :hypernet_sequences=>["svfilvdawzpmtygynd"], :bab=>"ygy", :supports_ssl=>true}, 
{:address=>"ttcupspyysrbukznk[rpewzuewspsqthbqb]yszbsclsnmbgoazsfl", :supernet_sequences=>"ttcupspyysrbukznkyszbsclsnmbgoazsfl", :aba=>"psp", :hypernet_sequences=>["rpewzuewspsqthbqb"], :bab=>"sps", :supports_ssl=>true}, 
{:address=>"rypyyznanxetdychyd[srdvpypvsmzquaeec]qzehxnsvvccjqbjres", :supernet_sequences=>"rypyyznanxetdychydqzehxnsvvccjqbjres", :aba=>"ypy", :hypernet_sequences=>["srdvpypvsmzquaeec"], :bab=>"pyp", :supports_ssl=>true}, 
{:address=>"nntkrxodbypdodgtj[lnlglurkrynztgae]twtxdcskknbsbinlnnu", :supernet_sequences=>"nntkrxodbypdodgtjtwtxdcskknbsbinlnnu", :aba=>"nln", :hypernet_sequences=>["lnlglurkrynztgae"], :bab=>"lnl", :supports_ssl=>true}, 
{:address=>"yvzxaecltitusbcfqv[witiggtqtgarfrq]bhnbijcfbhoqpojeuqw", :supernet_sequences=>"yvzxaecltitusbcfqvbhnbijcfbhoqpojeuqw", :aba=>"tit", :hypernet_sequences=>["witiggtqtgarfrq"], :bab=>"iti", :supports_ssl=>true}, 
{:address=>"urvfscylyvpyvpqwl[akngblyladvcuwa]pauygcletxnisgriad[ovsqsgvuccmdzqcwn]jjugrvjyydebzrjghae", :supernet_sequences=>"urvfscylyvpyvpqwljjugrvjyydebzrjghae", :aba=>"yly", :hypernet_sequences=>["akngblyladvcuwa"], :bab=>"lyl", :supports_ssl=>true}, 
{:address=>"yrfewhgpkihnhct[pxzsdirhdakahwdxteq]ygayoyiuikakdqo", :supernet_sequences=>"yrfewhgpkihnhctygayoyiuikakdqo", :aba=>"kak", :hypernet_sequences=>["pxzsdirhdakahwdxteq"], :bab=>"aka", :supports_ssl=>true}, 
{:address=>"iuauoxmsalkxobrgb[blehxxupivauaxkahxf]torbqoddhsksgtnps", :supernet_sequences=>"iuauoxmsalkxobrgbtorbqoddhsksgtnps", :aba=>"uau", :hypernet_sequences=>["blehxxupivauaxkahxf"], :bab=>"aua", :supports_ssl=>true}, 
{:address=>"ouluccjlcbcurdpkzg[flulmqooipvjzhip]qkxrrgvodksuivbspr", :supernet_sequences=>"ouluccjlcbcurdpkzgqkxrrgvodksuivbspr", :aba=>"ulu", :hypernet_sequences=>["flulmqooipvjzhip"], :bab=>"lul", :supports_ssl=>true}, 
{:address=>"tjxbenxjlgozxrtqdp[fqimqatlktqjwjdzuoc]fedjvxnqivqaxkvcw[lskccrwcsxulkabzp]orszzlxhimwlzfawjw", :supernet_sequences=>"tjxbenxjlgozxrtqdporszzlxhimwlzfawjw", :aba=>"wjw", :hypernet_sequences=>["fqimqatlktqjwjdzuoc"], :bab=>"jwj", :supports_ssl=>true}, 
{:address=>"krskxctpuowviqiqxu[xunkhvqyyqiqhyx]rcdhdjoqrutobnjpimv", :supernet_sequences=>"krskxctpuowviqiqxurcdhdjoqrutobnjpimv", :aba=>"iqi", :hypernet_sequences=>["xunkhvqyyqiqhyx"], :bab=>"qiq", :supports_ssl=>true}, 
{:address=>"viebpcquqeagmuavf[kxfkxsoijrjklkgtahh]gdxrwirjrvzjcykax", :supernet_sequences=>"viebpcquqeagmuavfgdxrwirjrvzjcykax", :aba=>"rjr", :hypernet_sequences=>["kxfkxsoijrjklkgtahh"], :bab=>"jrj", :supports_ssl=>true}, 
{:address=>"vcrftmfliijtpaqsoy[zcpypxlyshsruwbclj]mnwgypyvzdxnnie", :supernet_sequences=>"vcrftmfliijtpaqsoymnwgypyvzdxnnie", :aba=>"ypy", :hypernet_sequences=>["zcpypxlyshsruwbclj"], :bab=>"pyp", :supports_ssl=>true}, 
{:address=>"efvejswssxdrqggx[iqwwyhgngmwzwsw]dlkdcjxurmpsoceomp[scbledaqpgsgynjo]rsdxazcyjgcubfxlbb", :supernet_sequences=>"efvejswssxdrqggxrsdxazcyjgcubfxlbb", :aba=>"sws", :hypernet_sequences=>["iqwwyhgngmwzwsw"], :bab=>"wsw", :supports_ssl=>true}, 
{:address=>"ndbtkvzkgjsuyfibsn[gbfhvruiotbnbtvuxaa]xihrrhcnbnowthpdge", :supernet_sequences=>"ndbtkvzkgjsuyfibsnxihrrhcnbnowthpdge", :aba=>"nbn", :hypernet_sequences=>["gbfhvruiotbnbtvuxaa"], :bab=>"bnb", :supports_ssl=>true}, 
{:address=>"bgzhntrrxvjvhyqhf[tnyvbggtjvjfgratfo]hltqszvzgcutrdcvddq", :supernet_sequences=>"bgzhntrrxvjvhyqhfhltqszvzgcutrdcvddq", :aba=>"vjv", :hypernet_sequences=>["tnyvbggtjvjfgratfo"], :bab=>"jvj", :supports_ssl=>true}, 
{:address=>"suckcafpmeixlavp[ehmqotytcsxzagjq]vfwmytywcapfwlljl", :supernet_sequences=>"suckcafpmeixlavpvfwmytywcapfwlljl", :aba=>"yty", :hypernet_sequences=>["ehmqotytcsxzagjq"], :bab=>"tyt", :supports_ssl=>true}, 
{:address=>"bobcmszgphpejiwlwdm[wwjrxebfctqobojw]hyrcpguihwihhpmr", :supernet_sequences=>"bobcmszgphpejiwlwdmhyrcpguihwihhpmr", :aba=>"bob", :hypernet_sequences=>["wwjrxebfctqobojw"], :bab=>"obo", :supports_ssl=>true}, 
{:address=>"qqtluuthgrubwpqzr[kgebpbdpqekehnnuyuh]onnyuyxeqstunzueapk", :supernet_sequences=>"qqtluuthgrubwpqzronnyuyxeqstunzueapk", :aba=>"yuy", :hypernet_sequences=>["kgebpbdpqekehnnuyuh"], :bab=>"uyu", :supports_ssl=>true}, 
{:address=>"tbgqiatbujypfbjha[catabtthtrydcjbt]aujolgbocqymyeqfr[apsuwlktuaukokmldw]qllsjhthoqdlpykgwz", :supernet_sequences=>"tbgqiatbujypfbjhaqllsjhthoqdlpykgwz", :aba=>"hth", :hypernet_sequences=>["catabtthtrydcjbt"], :bab=>"tht", :supports_ssl=>true}, 
{:address=>"tanngpmswmpddgfpph[egmymqydmigpnpr]bymycsueiolsfyfey", :supernet_sequences=>"tanngpmswmpddgfpphbymycsueiolsfyfey", :aba=>"ymy", :hypernet_sequences=>["egmymqydmigpnpr"], :bab=>"mym", :supports_ssl=>true}, 
{:address=>"hvvzujphepxjyypzp[isabpxdneywzpzr]rjbcrfhnidqlywbgvxf", :supernet_sequences=>"hvvzujphepxjyypzprjbcrfhnidqlywbgvxf", :aba=>"pzp", :hypernet_sequences=>["isabpxdneywzpzr"], :bab=>"zpz", :supports_ssl=>true}, 
{:address=>"fcswktnxobrvovrjg[qsaxxwxgrenkdcpfvx]bmivhngglvcwxwgjz", :supernet_sequences=>"fcswktnxobrvovrjgbmivhngglvcwxwgjz", :aba=>"wxw", :hypernet_sequences=>["qsaxxwxgrenkdcpfvx"], :bab=>"xwx", :supports_ssl=>true}, 
{:address=>"ayzzozmdklbhitpd[xwlznwdbvtciozoykoy]ainwvvxkreuvsgdatbm", :supernet_sequences=>"ayzzozmdklbhitpdainwvvxkreuvsgdatbm", :aba=>"zoz", :hypernet_sequences=>["xwlznwdbvtciozoykoy"], :bab=>"ozo", :supports_ssl=>true}, 
{:address=>"zbhxhhqfeurqurm[buuctguwokorlkfq]extdceaqdkokhdaxzqj", :supernet_sequences=>"zbhxhhqfeurqurmextdceaqdkokhdaxzqj", :aba=>"kok", :hypernet_sequences=>["buuctguwokorlkfq"], :bab=>"oko", :supports_ssl=>true}, 
{:address=>"bmfbcrmibywamwmic[npcluivjtbtwmwxmx]mxyepxnjdabcuiexhwi", :supernet_sequences=>"bmfbcrmibywamwmicmxyepxnjdabcuiexhwi", :aba=>"mwm", :hypernet_sequences=>["npcluivjtbtwmwxmx"], :bab=>"wmw", :supports_ssl=>true}, 
{:address=>"yywsnxvznbcockrn[fnmwrszfamgerfhocoa]uxfgnvtphthtmeuyy[houdomoboxleqhrf]zznqyqwslypolnqef[ttbcfuirmlnwevhzw]dmohemntzpwivaab", :supernet_sequences=>"yywsnxvznbcockrndmohemntzpwivaab", :aba=>"coc", :hypernet_sequences=>["fnmwrszfamgerfhocoa"], :bab=>"oco", :supports_ssl=>true}, 
{:address=>"paikbyhegnbvcqa[kawvebmxrhzszrncq]noltxgnszsqxfbxbrk", :supernet_sequences=>"paikbyhegnbvcqanoltxgnszsqxfbxbrk", :aba=>"szs", :hypernet_sequences=>["kawvebmxrhzszrncq"], :bab=>"zsz", :supports_ssl=>true}, 
{:address=>"yogujlygnpdyhkxpdf[bawcwagtpbuwaorpa]noyoqlkcbsytnzywva[zvdbrjsxhozvyrugdnr]yyehxcwcnepivtjntex", :supernet_sequences=>"yogujlygnpdyhkxpdfyyehxcwcnepivtjntex", :aba=>"cwc", :hypernet_sequences=>["bawcwagtpbuwaorpa"], :bab=>"wcw", :supports_ssl=>true}, 
{:address=>"gxuxnshdgyttcjzvk[lsxpwpvsoquxuazidye]mfihmxgxumzfhnm", :supernet_sequences=>"gxuxnshdgyttcjzvkmfihmxgxumzfhnm", :aba=>"xux", :hypernet_sequences=>["lsxpwpvsoquxuazidye"], :bab=>"uxu", :supports_ssl=>true}, 
{:address=>"qoetptacgfcrdrstl[gpcfptpchpeiicbmfd]vsjqqgbwiqlndgmop", :supernet_sequences=>"qoetptacgfcrdrstlvsjqqgbwiqlndgmop", :aba=>"tpt", :hypernet_sequences=>["gpcfptpchpeiicbmfd"], :bab=>"ptp", :supports_ssl=>true}, 
{:address=>"cpjplvpmbumvgsduald[sowmjselnjpjwhav]flufpydujtzuzusyrr", :supernet_sequences=>"cpjplvpmbumvgsdualdflufpydujtzuzusyrr", :aba=>"pjp", :hypernet_sequences=>["sowmjselnjpjwhav"], :bab=>"jpj", :supports_ssl=>true}, 
{:address=>"rclnyybawbizurp[cptbsqptpvcuchcyncy]rlqjeblagqogxwy[mwexxfjhkiyoihog]slgmmhvjhpomcvgabu[xgipgcmbydzmayywci]tptdbfqkemdnuzvuz", :supernet_sequences=>"rclnyybawbizurptptdbfqkemdnuzvuz", :aba=>"tpt", :hypernet_sequences=>["cptbsqptpvcuchcyncy"], :bab=>"ptp", :supports_ssl=>true}, 
{:address=>"obscoqxaeartfjmeue[dtceaealpasuxsdoo]zhtpbqqfonksrcpu", :supernet_sequences=>"obscoqxaeartfjmeuezhtpbqqfonksrcpu", :aba=>"aea", :hypernet_sequences=>["dtceaealpasuxsdoo"], :bab=>"eae", :supports_ssl=>true}, 
{:address=>"fsjxwoamqjhjvyyr[johjhabbsofojaxccga]tqcnhtvkimixbyiqt", :supernet_sequences=>"fsjxwoamqjhjvyyrtqcnhtvkimixbyiqt", :aba=>"jhj", :hypernet_sequences=>["johjhabbsofojaxccga"], :bab=>"hjh", :supports_ssl=>true}, 
{:address=>"hinhkyqfttbnnou[luuiucbkkrnwiuqbwb]ujfitmunviqwhkiziy[wqbetolmyaceofd]wbwbxudxttgmtuxjeo", :supernet_sequences=>"hinhkyqfttbnnouwbwbxudxttgmtuxjeo", :aba=>"wbw", :hypernet_sequences=>["luuiucbkkrnwiuqbwb"], :bab=>"bwb", :supports_ssl=>true}, 
{:address=>"jgaozdtecqmpueg[bnfjhfyhdndzlkxrcb]esbfjomhfrfvzgm[wqvhdvpvrbsazqzgnw]lkmrymdcupndnoktuv", :supernet_sequences=>"jgaozdtecqmpueglkmrymdcupndnoktuv", :aba=>"ndn", :hypernet_sequences=>["bnfjhfyhdndzlkxrcb"], :bab=>"dnd", :supports_ssl=>true}, 
{:address=>"jogfshkvmshdacro[anluswkewepuhbemk]rwfxbxtmtfgxatwj[lwqompcrkgqzkajgrqg]ckjftivpzkflgbifzx[autylalyokqqlxgu]chewqmwkwewmwoby", :supernet_sequences=>"jogfshkvmshdacrochewqmwkwewmwoby", :aba=>"wew", :hypernet_sequences=>["anluswkewepuhbemk"], :bab=>"ewe", :supports_ssl=>true}, 
{:address=>"vhqxmrwadjsfoprv[imclvgvrtvqfbcllpr]kmgvgofdlkarrusoo", :supernet_sequences=>"vhqxmrwadjsfoprvkmgvgofdlkarrusoo", :aba=>"gvg", :hypernet_sequences=>["imclvgvrtvqfbcllpr"], :bab=>"vgv", :supports_ssl=>true}, 
{:address=>"kwkqhpdsrkdlhuq[njldfvflplvygnihg]hikxtejykexrghupbqz[tanglgtyodyncabh]ennzrvfvgcnlehci", :supernet_sequences=>"kwkqhpdsrkdlhuqennzrvfvgcnlehci", :aba=>"vfv", :hypernet_sequences=>["njldfvflplvygnihg"], :bab=>"fvf", :supports_ssl=>true}, 
{:address=>"udmbexywtscnesd[azofuoboewwundyif]mykxybobvefathvqkfx", :supernet_sequences=>"udmbexywtscnesdmykxybobvefathvqkfx", :aba=>"bob", :hypernet_sequences=>["azofuoboewwundyif"], :bab=>"obo", :supports_ssl=>true}, 
{:address=>"zrfmusbfbogbrsin[gaayijtuqfbfnxb]cgjsibujnswdmuhfez[rhatyymizrxrqud]wpvajerbhxbtrva", :supernet_sequences=>"zrfmusbfbogbrsinwpvajerbhxbtrva", :aba=>"bfb", :hypernet_sequences=>["gaayijtuqfbfnxb"], :bab=>"fbf", :supports_ssl=>true}, 
{:address=>"nticpuumzthsihk[asrmrtlzizgsvnvcxny]wjntjizixwyedcrh", :supernet_sequences=>"nticpuumzthsihkwjntjizixwyedcrh", :aba=>"izi", :hypernet_sequences=>["asrmrtlzizgsvnvcxny"], :bab=>"ziz", :supports_ssl=>true}, 
{:address=>"fahbkbakvcwwazgioub[ouuvcmqsmykbkhfhj]gntumiippgacbcl", :supernet_sequences=>"fahbkbakvcwwazgioubgntumiippgacbcl", :aba=>"bkb", :hypernet_sequences=>["ouuvcmqsmykbkhfhj"], :bab=>"kbk", :supports_ssl=>true}, 
{:address=>"gfgrgtizxajkaicjcc[mftrzuftzrgrwilsv]uckwgxywnamzjglbnts", :supernet_sequences=>"gfgrgtizxajkaicjccuckwgxywnamzjglbnts", :aba=>"grg", :hypernet_sequences=>["mftrzuftzrgrwilsv"], :bab=>"rgr", :supports_ssl=>true}, 
{:address=>"hzqfveaxrqycvuolynx[ztsmaipixbuhbmv]ebvofyoeponbpip", :supernet_sequences=>"hzqfveaxrqycvuolynxebvofyoeponbpip", :aba=>"pip", :hypernet_sequences=>["ztsmaipixbuhbmv"], :bab=>"ipi", :supports_ssl=>true}, 
{:address=>"dxnkgspqhyejogxstsk[jfgckouqypxttst]axtisjbtaviwafh", :supernet_sequences=>"dxnkgspqhyejogxstskaxtisjbtaviwafh", :aba=>"sts", :hypernet_sequences=>["jfgckouqypxttst"], :bab=>"tst", :supports_ssl=>true}
]

ians_list = [
'ottpscfbgoiyfri[iwzhojzrpzuinumuwd]orfroqlcemumqbqqrea',
'lcototgbpkkoxhsg[erticxnxcjwypnunco]notoouvtmgqcfdupe[hubcmesmprktstzyae]unuquevgbpxqnrib[egalxegqwowylkdjkdg]spqmkzfjnzwcwgutl',
'nesmourutitzqtolwd[rurfefjvljejcufm]jagkqdwpkefkjdz[cctohikipqxxbdjxsg]badmffkslhmgsxqscf',
'neakzsrjrhvixwp[ydbbvlckobfkgbandud]xdynfcpsooblftf[wzyquuvtwnjjrjbuhj]yxlpiloirianyrkzfqe',
'zmnirrxetiwyese[cedxmaoadgjjvsesk]nuisspyclmncqlasmuy[zxwlwmbzbjmvubgcf]hfqniztoirmsdwz[zlffqhttbpehxoabzhx]upmydjqzzwefvgdpqu',
'ejgpdxesfyoyaggmymi[axfkdoyoqkpkhusfwe]pnczsmszqevkqiwlfc[dqhzcqjzpgnoknmv]ldrjdhopfyctlqtn',
'zclgitkurpfdspcbk[yedvkzgbawpthoyn]dhvnmtxbrpttrdrio[drdahsrphffqsigrlmk]ykghbvcdosmtcgxdeb',
'mmyxbuoieontkaxvnk[lijzkcghkhiryhceqc]zuouxoicowwkhklyp[baqxxkavhepnpepnj]jcdekzxrpfucavdq[nxrhabcrumlshoitzba]httcbsbgoyhjpkv',
'fcrwgutcgcqizev[nwszwhfvqtdhrymgqf]iiahiososrpdafnt[gbkrardsossgcvu]fmudukrxbiqyrpi',
'gvmytvlyluvnmemhgjr[bvqbhytqwpyemefwo]sygljhpvyjnuxzjqy',
'zootaoveazcrmtbda[qlxlwntntbkjtkqve]vffdsbekufzemgwomh[vzllvqlmloffyyldfh]alltnttrzqrchacoiqm',
'ksbuxsjkmtzsfsy[shracmzkycsuqrei]qrmgsndwzkqhtojsn[innhjjhyfsffgsboglx]zhwuwgyrwmucjfii',
'mdnmunbnueofzddapl[wxfahokzfixiapig]wekvqzgvufgztlgldh[zwglgerouhvhtbrdib]xeogmvaqszvkdvxv',
'hunicsoijinxshpfskq[lniiseazhvpjiyg]wirqusdwvaiyatimhx[jntjijtppuekuvvzz]mxebkmgiqyfaglow',
'sjgpoxxqtfsltzk[jqwzhblplilweukbso]tgorxisfymrcgyr[tfbebfnnljlpcfeps]ahpjfbonoajtohthzri[tdgaokthtdhxpsg]ajcykosmkhftnrjqphg',
'hbeghglpgqnwpxqio[pcujpvhzhghnyjkmppe]jwcnwmqwctqgoxpj',
'apqmhkpxrtrfwulqbq[trthojavkcrlcgc]oikizlfqpukeudv[afgmhbusoqjubra]ajbuhxzuhecopcxm[lowqlmwiyvmdojjla]jrrhjmopywkqrhlgicl',
'mvjlhovwivdanexv[iaphahshtwtnhoeoqsk]syolycabjeiwtwtec',
'raugsxxkqxpsglitbj[ncskiewbnqnhxvojfx]qnqtemgvotsgnlgxyb[exshfmlaagkpxueykd]vgcwastyxsoddgu',
'yclpzeggejjnvkssg[jaxstjrzmutqmaqq]buvqcwkayhypitxnmp[hpxwubjyepaqhyhud]qhqlpdiqdhhgffsgtqw[ijhwhbvlbixaeywd]fwpyiwyrgoquoeuicxp',
'xwcoczwpeprblqvdsze[fcqzupldpqdpibi]peaetflnafpkrqz[aibobqkhvfzpwaajxj]mzlrkrfslubibbu',
'nvouetegmutetgw[keqvyocxdetebkcgl]qfhnyfdnjqnklpad[swuvsfhrnzsnatb]zjwqmrmphlgwdnms[hdlfprihcbcemfn]lrraefojxvtpxljil',
'yxcqysoxpbwjlqjdp[jinwxwcdeflygawd]hgdgruqilmuzuzhsg[ivpimcyrtifudwjgso]ostoopidgdzcrzzyzts[vvaiuzzuzywesuzk]ccmdnuyihasnldexf',
'rezxczwcihbkywyq[sdzzflizzygfiovwyw]jhtiwvelkbaqhvnylca[xpnwnmqbaawlyqz]kftcwdejxaznztqsbhy',
'zitlyztihmeogushh[wpsygveulmddxdzvwvt]auvwghiyvkvfxyzf[ccnkvkboczqbgcmekt]hkqnuaoeffocspxkck',
'hshzrytllakuifsbuap[znsqxjzxbeewshkb]tdiohjkqimfsaijvmvf[wxvmhzzkjopfxhshsol]qgjutmxlputvudf[thwwxcavnensivbscm]dounftyvyaoguqzy',
'fnlgxejzkpocaonnloc[ojrecrvcmirtehjfcvi]mrafnbifqfcqxpmqdrb[obuqfqpyrkeinweynd]qceebfqvcmnowjanh[ejpkcpwkjfbvyjmyzoo]hhjyeulunsuagwq',
'hizeoqbkkesksvtjotj[wkvmcgctdzwhzlubt]aegcgfmdneprdbw',
'vphviazdmmvtcyc[dcomcirqycymvqkm]meeikjmqliqraeqd',
'aalmyxywwvbwwttad[daxeeneiiiupzvqz]cqcjxzindssjrqb[komptxyxwgtnuedefro]xfbjflfujclbqflke[fpatdmophhvpcmwfj]cqbuduaifbuhwiy',
'kjgjcnoipwnlqnk[hpukxdqokakrgjgjpk]nvinvznddzuhupepemb',
'mywakayudrxzofpri[qlywfoydoqmsmaoygp]xpwmtcqqfqsmsys',
'ztiyqybtvliidsq[mvhqxpqunpsqouvgrbx]qmhkzbqhemycwxeq[cdadaodqyhjhelanr]rtrnroumhiwdadrbe',
'qvfoyofzmhctntofr[xcokguepiaisrpwewng]lwwzyewekuamxxlepz[vybjmfsierveheb]bzvvxsdlcohnpmgir',
'ztncnhqvomvfnkhca[ohbigcgrevrnpvuwgpv]lnjucgcpghvtzlrgkh',
'cqnuuhyddzalcxc[fjmqzkljrqjbexcxxf]pbjsvyixepnkthndhb[xztvuzlknucygyvegxp]nwxzswdvaspdufotcxs[bivsecxgawosnflmfd]bvdtxxionieorvecr',
'txqpvnrfxykothvao[uikgxsmnyxwlobod]tddprkiwjtdcwbobzrn',
'kqxvmryochlslekzhl[ivuyfsoefnqqtwspxtu]bytaafalzlqvjumuleu[apezlzoaspstxvknv]mnkfbppakmectmiafs',
'vungsqgzakhfjlbuwig[cgydynonrrgfswomgev]lkyqpvlplfsmznc[kttzkoqpeplpfaoheek]ssijcynyhenhnwvd[hleabsbwqkqqnvdd]xbbxdphvgzmnauj',
'oagqrhpfnkdvvsqemp[qsjyvadkirmihtfezev]vuuantqauwqrbyzxpev[mpaqvjcfntbdcpdi]ghgstpggptgbvwnmyiz[hghmuvsvhqxvxmmnx]owoulisjbqpndzgt',
'rpetcixepthhnydtsx[dvivlhhlgbxftlw]ensdqrwytpwniviwh[uierkmawdkijrbrbb]ywvqqtldiulgtft',
'iruarpzjrxupbdovqlk[cipcsklubepettbee]jfnvwjcgypepsbnauh[ncvfofkqfotujbat]moqzftmyjreztaugkij',
'kthovdomnavxzkrtg[utmtbhgqydotlxos]rtwopdppoocytum[ptdpdrndjiboffigipy]fwxyvpdnlhjofwjtwx',
'vitzjdhxjjossygyje[vzysmvvgddhvkufqb]fhwstpatifhmyespsay[mrpnqgygncsiwial]cwbbaisjnqrpuzca[taqkhmlvfdelcrzbryp]kwsdxlkmoplziobgct',
'zvhafubtbxcnggnnec[khfuhiaikrpowmg]udtuciwamjspaojuks[wlzjqwtmrfrfxmxcfd]plaqjdorfrbkkppep[exrlzahsxksdqsllkn]fooqtqpmnglrwokq',
'cjmaltrbirusgyoirp[eipxzkuhukkdcdh]iqyymukrkwitywb[dcvtitgqvetxqip]sldydwlrcdcrljhzu',
'vvzhcfuecgfvrxrnquo[oqgutuxthxlcxhpke]liqjotlxzbmsassyxrf[colshvmiwbfjansdg]vggdkkyqrjvthtvp[dmozaqtceghrabasafj]lnsoewepnlbqvibyk',
'wiuprpjfojcowmy[vmrpruwhtzbwyciid]ntbkrodejcrwavjfqfa',
'nbdnniplhgrqkrcd[thcyuekybfqraxspek]rlwhyqiavfrfglg[luswlglyiuklvbuqe]mdgjepgjbhuyqkcs',
'rfqbvdzxrnrbuhvw[wzurtnrnslhoqkdoaja]vuxsxofemkrjzqkk',
'afnnxrxdhbqqixcli[msrrsiakxynnwiard]tzanbapzvxtabeuz[rbyqhswrxrofedlykg]phyilynmscckkxgbhks[enrqxrwqiotksdor]phnmohcaqxspqhv',
'tsswuaezqpzyevei[nolctgupccscwsj]serolamcjmqaawea[qgjyyldemhsqivwmvtn]rlmxvchrccptrgmmbko[qtiqgvilvevjvlkxc]jjcnzdjdxycczflslq',
'pbbcmecbydtmjigfn[giiambqbdgbgntq]zaaqvlpkysxuvbgbo',
'hcbohuwdyeacvgmbmea[mmpvzmjiryorskh]tydknyaqhgcxafmqj[ejadhaojfjlsfxs]duohhgjdfjffvwzcgel',
'ltlddqcbkkayshw[qdedbdppzuqdhfaxt]doedeeehsibaylpsnk',
'wivyimuplkhmmkxioub[vqfixqklclmrbume]trenzswrpqljwctfat[ulkqyvjjpchvkpd]mvlwfrclcfqziho[pbmrqudqsivfemt]osmrlwtwstidtwmbmzc',
'vrjvymyzflpaqfy[fokfgiaiyyzruyt]yvfrfomlsjqkvtps[mprfrwzeokyjmdetnl]znjipokvzxljjgqaw',
'xtnewbseisluqott[ukktnadfrptzmvmnmwe]nfevmvifmaaubdrytcb',
'zahhurbvayisuhkxluc[dpkhtfqcplnlwkr]moobahksmsqtmxasrw[oyxemzzmvwvxrldebja]tqnquzqoslugwcqcwtr[vibjzqdbmsmtxckkkn]ylujuamatwbexgo',
'crzkarxgbgpitxjeunw[xlonohiojoepwnuhd]kalfjqpazwmwruq[erssxjpfzosbcta]exvgtqljewfuwioyq[syaeqtgrgswbgbetkzw]ofnozzjtykajqcuc',
'djblesvduxlxfxp[grmuswjaheivlqvtst]yrqstsaryoqejwkd',
'kpyoqmyglnrmxculu[tuyuqjronsgluls]whuymvpcdxvxrimvmow',
'bwtgmmjbtisnzbnyedf[iniovvuewpetwsg]dgvjyrzfrqcozekvp[xsulvxvvtwcxuvbxau]vvjyodjlbbjxigdxvxv',
'rvfdfyaemhgyeynw[hmmkdfdhadrqkxzzmsj]ugfozgghllznjhdxw[ucrgusuuqthlgxx]ipiercifxtkghbkf',
'zkcihebtrfmiryqkd[ybedpynfafkkrbfdm]ovrsmnhexyqblafad',
'elgbshsnykhiyndouao[nhumkawagmrztsamd]fwqupmyuogneywsyhub[zzcemywfdswhvjpl]ockclifwawqsyzt',
'oiksidcbtzhhtnegqa[vdxnacjfxbcsjzqdq]ixvwmdqdaleuzjniki',
'ljywtdshrtzqzrln[lqzqgywtrpgszaigfv]vjyyvrbkjdiiminfas',
'xmomvhstjavjyisvhs[suremlzhaiwhikzzojb]urbiiuvmveiapcybgz[botikbmkcfsghtgtcn]jbsrxdkpxnynfibgxyw[agdmtydfehaujynym]xfpytnqyoafnuott',
'xjzhgefdlodsdahv[ihwwnfbwhcjdbrdixy]kmsckqifucrgpocyvc[pudtuuaebkvsrflz]qjfwaaylzyhzerjbhyn[fsnmlxncwzsdsqp]edevlblbzmwkgkfluke',
'jbdmjeyxyksaonmswm[vhxyxtashfdrzjzytoq]jpkbmclxjtprrhmaz',
'vxishfigjpmdwufh[oykzgieieiypyrqaxdx]etgleieyrezvbcg[scrtyttykipejzmuhy]oxnektqrkndltaixnj',
'qgpylzwwdjxmepsc[bumaitztsvayatapvl]gotathwcrjrsknrfuk',
'qzkfvuxmfneyrpysh[clufxjecvedwwegflp]rcxzfazrzbgogna[ogoplmljfwvizwniudc]yewvacqgzcjgdnmasw',
'gqoyggrpzhfgrkjjw[kwhwkctzmjdpdoeey]ngurqljoormcjarv[bmvadfmdgpwpzfiiv]fkfqchwhedeymsa[etqtnxepdmolklpa]tywoaqpoowybxcoqq',
'zalveeaqakqjhfl[uypjekwlbcplfcasa]sasiztlswzyhvpd[weglkkwlrrvdvfd]mvsdbveypnjsymtjka[kroszrkveyammdqqool]kgmxohwwgmvcdludvdl',
'towtxxuitgwhddsua[bydcnwqycygmimbrut]cvnvgtuiuduzjod[gpazublcnojkfnnvn]rozlfkywwjelmry[wvtxeleixyqstxjqed]vsuvzaskgyooigoczd',
'hmddytvxqrazumnnr[hpeurkbdfejhlfvg]pedwizmuhmtpdwh[efikgkrhnagpmqypzx]ltlncfegswhwcxa[bakxhwhtvxcwcxtmofk]zwjvbxyvljlfaie',
'khmctigslwdgzghkbk[veaqghpizqwjxlwcf]aymehevjgpjgwruhyc[hzgzilbhyoazljsk]jocgjmooxqxayzsa',
'lcgvlozzzzpzxeoee[zsvjydznyoadkvyxlsq]wqmgagbkerqyxjnnx[isukybwewezizpll]odqwazjphoaqhzltms[gtqeysqpwuuohdbhcnx]yqtvojobgaluizidrbn',
'kqbwgctrhxwrkkedau[occltggonhshykttsrr]snshslgqtlgejanlg',
'hwjwuhdokecprunbju[jhftguwujsuetdriyu]vcgpesthcnwuwpwes',
'enzmvjyrzypbbtmbvx[izvhoqpjgqgmmvricf]dbghstbtqgqawqjr[irvprevogenchjy]gbiwvcxncbjjvwmshsx',
'dlwhxttrwjlxlit[atmcusmqvonodkfwqvb]ilfdsqjtjbimpaqht[zsbqjwsrgxlxbjqmulb]feblytbapctmfuao',
'oyztkiwsxqcufgqk[iyxqvktohfnoymgisag]acfhjawamdhawitvjg[npflzsugezpsmunukqa]vhhxnunvyxjtehyvv',
'zjnlscyhmjmoofha[ezglbbmqulybnvf]qvbharzbfbbustsm[tdeqjfbfxeiknfr]chpwwntytidtnnjf',
'xphruwdeuqibzdss[ubuaiomstyuqgcgzyn]upkpgfqmamubaqhkao[ohjojarsqpjldirf]ianntdwcgclwmyzwjh[qqeajbudidxsqfw]nenqeljkdyjucrqnsgd',
'xuydzitbfqwpaafru[jasqmetengbkljylhse]wkqxkjwkoipjfhkafnt[uolbyhzhmtupebneng]pcjjrczeczmoenefu',
'jgvoejrytatxvfqwt[hinkejefiqlrpqy]cgmvjuyjejpinjunld[qcdmwbqbqusirlxh]udhmheqsvmqmczbbofh',
'qffigxgklwwslnts[gwhobujjovmwfmrg]menqzjmmxrgchttltek[fwegvyhranuutxgxec]fwzgoobvkjekogpfscr',
'hcqlfxoahajthjesrdy[nammwfgfdqnjewunwz]pdzecgfgatymrrntt',
'vwpdygtfuvbryipr[ehziaqbphyzzdolbfsv]rqxvfvafrauzncapu[dvqlgdgkzgpbjuihbl]sdtldsvjvvtlvjdgd',
'slubhmrmovzbgdw[dehwvsngduvcfkontgs]zeiqylnomqgevvikm[oubxjfwewqtdjwacb]mqjinmndnakfemp[mccapdxlrmrevbuaas]hcjdpjgnoguztrdjgbt',
'sanarwdtnkaemdsoj[ojswyaadxpnpzcm]acjrepbjwnnpncdf',
'uvankqvbgxtgignh[zaimktolqipleig]mobimtizmlgqetrxkft[kooknezmesqkqisip]jdpwwsisdorcrryvyjn',
'eutljtdlueiugunxsy[bmbgyvpiruvvuezir]vksxzmgftqglhrowpk[wphxqgxjmzhuqrwhce]giazmdryyjldglcivd[nsicphjzfpfzlhfymh]pfpeazmsdcttsutbs',
'tmdniznfpsrdaivxpcp[nlebmzzfjfklqixhk]sbusrwexlbpswiyslbh[tuvimwrkchmarbvl]ykhoceojfjugoim',
'wmwfxoaocwtzuhvenl[yzpbmaoazbchjxozl]oulzkybjweqqzml[ydkamvkncxomqsibme]fcuomzdfejvijxeniaf',
'clyxvevuyzylpdud[jmwhfhkzrzzkawp]nwcvtlwlwnbebgdz[cbnfsolnppgafml]mxhbrzrialopbbk',
'hiekvarctkixnmypau[dafmuxavuaosooos]czvsosvafizsjiouwi',
'sfsncarxehtgmutj[aqauaojoqabkguvan]olgokvyhpfjzyqgvbcy[fsfdkbxhstvxlkzb]ozwgbzlhrocqpjoseq',
'shzexlixgxazcobmdvz[bvrebdcpytgplvii]gxdgzyoqpmkqznz[wuywofxihsgxgpcksgh]lwqsslamcrmkobn',
'clhvakestwquwywsohs[ubwecsjptinhzngw]dvjcvukpkdrgpbeua[svetegijnnbtetpgfu]nfejtethkqavpol',
'cfjwosfrfjwgwognyjc[jiwoynoxdngalmreoq]otqvhbkwlkpqatkx[wwgwguxuzwlorap]rjuopkpuaftnkdeg',
'dcdcoboftwhtitlto[qdqpbbobdncixqwhmn]cdjrukqmcdbzwji',
'maeefdbswszxotz[sdfwswrwotoblvzk]bqmhwlxmzvjnorn[phhhipunsmqfmormtk]aasvyeqeffypmcop',
'iotcaohleclcmtwp[zirjcaznbsuwrbbspl]vdyhcyoroztlltnsubz[nmnaakmudmmobxzk]xjxybbzqfoibovwhr[tpzyhrmupmrfoeufsv]nfvtlfdnynqiwrmnmt',
'bsadpcmsvgfxbpskka[bqcswpjvfijomiajzjv]zjzfrshleucdcwpf[ipqvielmzuykgbs]rsvzmpmpfahujfofx',
'honratmzckbtooiwan[epebkioukueaexbb]xyakukoiqfmtdhvxf',
'mrvctdetjidibveb[msvevesuydbqwrytbh]yiliwznzilsslmachk[mqyuthyalilcmdpxz]ctawteeyyrsbncp',
'xhqazvqcraogaog[efbpamcmboregjesn]vinozerwxjyrytyd[vmzmjnevhaiidnhiuw]nvzsnlixrdzmzvtgfy[veacynylxxfkeep]syokzdwmkkhirrz',
'uutahwebslojhtl[affybmhohxqavah]xocumtcofvavgdgl[xlypyhazihrgfwllp]ptfnqjlzbaccyoaawi',
'jqajvhvbrkrynxg[yekfvwkborakrkfl]bovxzhceonjclmgecgy',
'jzhfwqxoqsgnrnex[ccrtrnroigtbvrnjeji]bbhfsodufjqhjvplii[mcubmtdgwttmmnazhpt]hovifldmlnbzrwqicaz',
'lwxqnbbzjlckuji[bzxykmlhlgjosvs]fdocjjmtlhlghzvj[snveavqbuhnzqktmyur]xcoabwwqxexqzakbrh[iqkdvngcdtlhlhudqk]edydfxflcnpzrcjsppt',
'roximfsrbnzyzjmn[bqugwcdliqyzyaqiupv]rpdidncsfgexyncbg[amzmtmqwzipkjfy]fqnscfsjmxjlpoccvfd[bpebfxoinyaqsgjpb]dykidfsbcykdobqe',
'zxqdqrztephcpieqdi[rigecfyegojksvjmya]rgygzpdzmpvogeurni[odgdyrqmqgrcmhfcu]ggdgejoiritcrdxxu',
'phuncbfvyiwxfour[oauntpjxaqvwvqn]liffvpoxrbljogpcwvw',
'hforuldqhrolhqsm[gofgjhapikxnhhdn]xgdarfanlnonwdielb[hvntptxixclnlqphvq]hvvdpsmvsveyaiubt[hiiscphavjogadmj]bbfjdjeecrhhrspxdpq',
'flulgpwvsikwhpzpza[pmlcfhtmvuiyoidfbfh]czcxxurdakbxizbbfb[blpwjusbzbdwugwbcv]vltmmzttxuhooid[hlbpbqjpqyclebkye]hgozvhgdplllxiio',
'augjtgfyoatluixgc[atdsbsouunywohfnk]dpghgakdvfscbapsm[nkodybopavlbeikalqj]myhpkcbsbkbjfgj',
'xeyyjiqvduxcflt[xiqxiqeepbpkkydtzxs]vbpbdsaivyavnfwj[rduzjulshqiluheud]inliammiyxregzbsrkt',
'exzcpmjdjiagpvsvin[aontczoixbznfwsvss]hdlmrrdtbumlfvril[gcuizdwjbzyhttw]apadljkbcsylwgekv',
'ctautcpnnufupce[qtydhgcjjqofrfay]lfahmjfjyppehyp[qzaxqkpopvwzqofe]rkcqkjpgptshvoucer[qmczzorygyrwbxiji]zljzfavjmwawfrfr',
'romqbwenzvevhyq[ewpxvrduvqewryaoct]wxgowmsdxrxjnyj[obazseiipwfmbyxhkdv]gjalmcoqrquvdnmzacu[abzkksqdcduhkizuzxs]uzuazfdegdfqjmmr',
'frvysxhaafihjpza[uuwayzhynhgliyxcc]vdcjfobjuqddqibjef[iusgoufujvqkfjt]cejktzeuphymtswrxj[nthrscqmjniokzsq]tnsfuflhwdkvsrlm',
'nsrehcsbptmpdeskqi[rpcpoctimqyccgnpnfp]peakqjqlahqkqfgoc[irckfbpvcdodsmwm]oxnqnxhwmwflazjv',
'bjgdyrlrhtkbqrjohwj[gcmcelqjvjadxqnj]tlupekhzidsrscrf[oqadjqqatohbjwxrneo]ykhccsunlyamcmmk',
'mhwhttcwzcntsbufi[afretswhwxhwkptb]srrajfoeahmhecarmu[wgjragqlbpfbfpd]epytkbjxmblfnkwhlhe',
'xfoshshomwdgssxla[uhshvhbfofuhdsqk]zbzynuiyfagqpemuplr',
'gjgmaueywnbqdvgf[tpheftnkpnlyujv]tvnqzdugoyjybxfpx[lnhefqkhesyicqqgvai]dvdgtlsayhtscupgikg[fyjgjzcrucldwdd]ohlycgvvdatuyvduhuo',
'lympkckqyhgbaumc[oodkeqjyhckceptyqui]ejkkqbitfscazcx',
'tllvdxtvmesnmauwk[qaomhmguwvmsjbwrwz]gvzyhjymfhmheexe',
'bpvimxocqygiyfak[kocimiojschpxlmlbh]oeohxkrlnaramquwz[mvodjkrtgwsyshboxo]jmxqxvydlieugen[qsqvwfzcowdvxzeflfz]eoysyaomzucvprpm',
'acajjiclnscuxdsyxv[axykpgkepnjhrhfgqvr]slbbdyluiqetchbrhrm',
'ktqkqvqxohypotivf[nsytklzqsdqgtjsrved]beidsrlrqlaaykv[bhalrlzjhvbdtjcmig]awjesirwjnmfjdslc',
'fzfcqlltfzjujqeym[jeaiiecptdpgfsfccuc]sfsekysmcjtdxjc',
'xidpschespoxuwka[lifyliiagwhtynahwr]mophvutwbflkblhzp[ngfdfvwwlfuyujsy]pqgdfdrrwonjcsxyb[txlrkdplwmwanoxhveq]sirdziimdysnzdrzt',
'eobvoofynuxzuaudo[icwrahzvyvejahwlbq]ewwnptijkewsppx[bmqxtgqmosyeyhcbsvv]ojsamjjroupnfxbygrm[yqqusonrkvfmwpiwo]nueolsbydgeyemas',
'axhzhgcgbqdeauomnjz[hbuvuiuidkykmvbd]yjddakntyygztrc[mgxbjwjbkzwnkybcgch]orbyhhpqxylsrzu[mygxsbzjoicfneimx]jddqvyyavgguqlqk',
'apdywyijusgxzfj[sgbhrwbwywwisyg]ssiiosnfconncgiy',
'njpftdmpmkjwcngeot[mocqjgcycgznvcqjv]aixpwfggjyqyemoz[fmklzletfvqdyvvg]mznoxpgwowvjjmus[prrehzdyfwwuxvhl]hqppujbqaizlzvv',
'vbjenrifdqsyzlwga[wmjenjnqufhqohvgc]uhrzouilmqjnjigwpa',
'udumujkujngtkcfv[klinhdudyghspdsga]gxavvcsxqxvaziqrmsm[htseffbehxafyhoars]ghilivgeuuzjlmih[vtjpcrmvldjluqdazun]mebwzbxywmrfhet',
'nobwzchgrycgkxc[tqoxhzxeorivdtdkde]ctdtkwzsvuxfgjtjg',
'vogrpuzrevmatdbqqx[qolpybjnetsxcqfcvbc]ixxogojluwsdsldl[bztslfanuylwdld]xanhrzxetowrgift',
'oxjkoqahhqqcxcoxksg[bouywtiajyfmanxcx]xgqpjxtkaejvmqckkuf',
'vhvuumgtzbrbgazpo[epktoekzvomswsqq]bbkntocwjpaxaoc[rnlzbqxqcuyltjxepz]iaelcpyexpoqavcbepy[azyksbvkvgmgimw]kvknvptkveiacqnzll',
'rketxmupdbmrircajep[xfmnkumekemjnwki]zurvxfxnrrvkmkrhbxh[lsrwyjtfjairiuwbaw]dyvmozkzkcvmunw',
'jkkrynqxqlgxukyfv[fugivxklerausdl]shcuiixkbmzymoxv[thtakgbdzvjsjsera]lmpwzqhthoottxvp',
'qzonwqxjkpwqier[qmrnrkkwruteiijirkf]xhnrnahamaegfla[fzshmzjiczdyzqhwx]acjlrknukkbewao[afpeaepzoljqxcwvs]dlvdxhsoljmqgmvzf',
'sxszfjmiathxoqnxg[smizlxpwmelqjlf]etoglecoddmflqma[hsggyxsxkhhshucgtnw]oqzadjxenphyexaqrb',
'rjrldatkdhvzvgcux[iuhectextisybzvz]vycerefkzhnmdyg',
'omuyrkrubieiduzegr[gcigoszvylmdrlrc]jtlrlsgqxiqtciehh',
'gdbeqewbrhyfbfpeti[yvyiclmkwzelbqi]sktocytuvyvpcia',
'gnfkqxrtauwnkhfoyc[msfhopavdyhpvpttg]ewuyaxehxbyziwmxd[iyqrfiudsalpmpk]smpmubdejyevdggead',
'tdwoqxlhhaqkdmv[cxayaazioswycmwj]pkenayaygxyrtqrqugi',
'ytcnqprainktcjei[phwarjaicrgistkt]qdtijjhbywixrie[llwwjrzrxhaqhie]ufaezqgmmdhhzjzrza',
'vzcnrbtoegbsuglk[rqhhdwpschucsvlnq]hzjzijxkcoxpwhi[glryptoeiosdosoj]fhduvpzlbptbehtt[yigihwrodvsulsrsh]numkgigkznkushjc',
'nvflxkucsnbsltnp[iqhnmiyolnoxjzjzjvl]ctdsnjzjaflstsy',
'glmwwqvembkbsnvs[skbkkvnoycklltrnyrd]irlewhaeagdiojbr',
'yxjwddyrzrzhqrarheo[dcayrrmkvazrzzlpqh]gkvbwuimfochtndis',
'uhwbwhbgkrzntdxrw[pchhzpiwclaasygyqn]oalmglktkidoijgyg[yugfmrxigwwqldfsfb]otdsjvxzdlsdhnyk',
'ubsustsojocdyjv[obkxihfxtkbaeusurk]zmlqtgokothiokq',
'fvmjytywcfdqfmfvj[nhufehmupvzkcrtewz]hyxlzunwnjccnnphrsg[hrfqmrewnweuyulb]hmqxiwaqfebkvxhv',
'peqyzkuviznbwojhtys[svfilvdawzpmtygynd]fpfggygzketpcrrqx',
'ttcupspyysrbukznk[rpewzuewspsqthbqb]yszbsclsnmbgoazsfl',
'byjykuzyigqofolpgf[cybrboapdfgimjwjm]oczicilrowczdlcy[tyaduotkhfvyatb]iklhgcjvfdyypdrdbz[dqkfqaadlcnxfofsvw]syuiaqaemufewlijxk',
'wvrrowjovflnwpjhhrj[dqfmznuqmmttqtdqnp]wevjmhhfmorcrvxvw[cnjtxcdcketvdidcbu]icghhdkudxptbdcdhik',
'rypyyznanxetdychyd[srdvpypvsmzquaeec]qzehxnsvvccjqbjres',
'vgriivdekqhhyzgmc[lkzxlushgdqezkwkbv]aqtzbkzcfxrkuwkw[aeubxxnhyhlolauhnu]qphfpphyptbmbvcyutk[xscabrjhmsfredzulrm]torgsvodiuuxkgcp',
'yrncnxrkuamoung[vteffidkspotxmwhna]lohvncugddeuevq[ueuixhkoouhzzfucs]xgwgddhczhiovgacg',
'nntkrxodbypdodgtj[lnlglurkrynztgae]twtxdcskknbsbinlnnu',
'aenjhairjysyrfylli[ksygiscororwmpcbpl]mdggayipjsxxfhz[zrovsdxuwyxjjbfm]vpmedxtfdporoono[zfnnenxocrbtapmnezl]odykztbwvuvlngxkwm',
'rbzuremuvpunjopiw[evldkwtjsfwgvdl]unsafmnksqehiore[ipvgyeheeuobibga]ohwjoehyibiihubwuo',
'yvzxaecltitusbcfqv[witiggtqtgarfrq]bhnbijcfbhoqpojeuqw',
'iwdziuryoqkhqzukcbq[qdoppjrevjmjuod]jewewfyupjnuydkn[ysbuocvxflmhbdhlb]ggjdqbzqfekjbbf[ubywismzabwewsrl]fufmyromzqrxtxsijkl',
'urvfscylyvpyvpqwl[akngblyladvcuwa]pauygcletxnisgriad[ovsqsgvuccmdzqcwn]jjugrvjyydebzrjghae',
'yrfewhgpkihnhct[pxzsdirhdakahwdxteq]ygayoyiuikakdqo',
'iuauoxmsalkxobrgb[blehxxupivauaxkahxf]torbqoddhsksgtnps',
'ouluccjlcbcurdpkzg[flulmqooipvjzhip]qkxrrgvodksuivbspr',
'kfyocamgrbgzslp[bclztdzvmbyetlgjk]llzxtjeauatwnnpkrvp[pxshjlevsleipkfkmf]xblovddfkfhviqulap[zhqfznscbngsaej]rjfncwzuuqwowdhfk',
'tjxbenxjlgozxrtqdp[fqimqatlktqjwjdzuoc]fedjvxnqivqaxkvcw[lskccrwcsxulkabzp]orszzlxhimwlzfawjw',
'krskxctpuowviqiqxu[xunkhvqyyqiqhyx]rcdhdjoqrutobnjpimv',
'ikdnbajyzpzbtzjdey[fiygpvlyluerdjvcdc]hheswtvpmtvjochdsih[kmjnhhmbpokaxsrf]byzdcdlvgyorjvkujyl[ttxlhbnifbfgmvs]onytmkodkklacgel',
'vjyzycrsfycfrookru[iszkkyvwngsskic]bnnqauaqcfxctnyofoi[tlegfofrqiuqlgkld]biryppugzufezftpjra',
'siffwvlfljwbcndns[cawuqwatfhgwsphjn]twfwwneebgzxmqyrhbr[awxuvozbhlohuaxim]dykizkumcmmnwiwdx[dikxuxtmacvaxiwih]mscklmepmcgjemwtvv',
'viebpcquqeagmuavf[kxfkxsoijrjklkgtahh]gdxrwirjrvzjcykax',
'puivygxavmlrxwkst[qvtxsgezqcquyae]brdptsxbxnobkvcqclm[ibxfeuecufosgtzhxg]vziaqziqriftdfrpnll[bjfubyvxxrbsjbqvi]nnlbiuncvdtnnarm',
'dhbhmlhsizoeldofqs[qcypvphfozxibpjdo]idntecorhucvlufrwu[naoixcxuqlgsytnt]ehsyusyugbmahyrn[djtckrolqitsztwtuq]urantneyeodhvorgsx',
'vcrftmfliijtpaqsoy[zcpypxlyshsruwbclj]mnwgypyvzdxnnie',
'ysxiybmwpoygkyle[xaaughrlqulsertp]iukezabalczvwieegzj[wlycqpkbqptraajl]mjevizxosnolkxnfwxc[veialybabbpytrf]tpgpqighdqgphcwoysw',
'zagsvkbkhcrkvnukl[pyfiiavqjgonrarga]antgzbmtohtndzgf[gkvovvdgppcnyjifrc]lxdhpometcwlkofze[fpxwacqdussynpwd]mymrmftjovoqtkuae',
'efvejswssxdrqggx[iqwwyhgngmwzwsw]dlkdcjxurmpsoceomp[scbledaqpgsgynjo]rsdxazcyjgcubfxlbb',
'rlkrgjrxefztgtho[tphpsircgzsauqfew]ridnbmerksozxzwx[lcqwhfgiihdzgtgudp]whskzgdpjubkztb',
'bogowskdtwkyhtdpzw[uxvrferconwfnnj]eukencoekwwahhefvs[xtrpjeahwpxbwgogfmh]axqvtgibzojnfcku[zhkpmdtwlogmypeqc]jzqywlhocshrdrlgd',
'ndbtkvzkgjsuyfibsn[gbfhvruiotbnbtvuxaa]xihrrhcnbnowthpdge',
'yrgxyekmldicpvo[wqcvsbptigcqvzoet]jjwvbjbshgmwttac[ymvjkuxxoojchqomnj]tsapoddljyrehrxrke[ajspkmvbrzxrxlpzw]hwymrguaqnefpsza',
'dmlshfvkrzncuuoo[fddyurlzqbpqdidtkrs]kcewmacglikdszapy[fltgxlltlvysvylrl]rgovwrvccixdullrof[bqkrpxjupbbrdnahf]ebmiiwmxkutltuxwrds',
'bgzhntrrxvjvhyqhf[tnyvbggtjvjfgratfo]hltqszvzgcutrdcvddq',
'sgzcemtrlzdjijht[wtvzogdoomtmhxcwckm]nmvftmtbucjnczm[hkqmnugntbrrsphbmn]yfvwwzebdqjkryhm[ydcjwepsqqrwnhkpup]tyssdovqgkhvvstvd',
'suckcafpmeixlavp[ehmqotytcsxzagjq]vfwmytywcapfwlljl',
'vblctxriewmbbpxo[xsgdnvmcmfnuejlrtz]iltofzajbcezlpy[wnfixwfqqgseisa]buystfqzokvletbzv[woumxjkmiqqstnt]ciarbpnsahayntnv',
'bobcmszgphpejiwlwdm[wwjrxebfctqobojw]hyrcpguihwihhpmr',
'qqtluuthgrubwpqzr[kgebpbdpqekehnnuyuh]onnyuyxeqstunzueapk',
'tbgqiatbujypfbjha[catabtthtrydcjbt]aujolgbocqymyeqfr[apsuwlktuaukokmldw]qllsjhthoqdlpykgwz',
'tanngpmswmpddgfpph[egmymqydmigpnpr]bymycsueiolsfyfey',
'dumehssexnwcppac[gucpccbmtrdgoee]zpcpjjuztjtgxxhzroz[iizviarbucshvccj]xlypepsxxhxphttgc',
'lcvkjzckpkeyzyjgtwy[osncmhyofupofwscd]rysnhkmiqoqulyu[lqwjsxrgpkpkgxnvhf]ftmywmwfpckoadd',
'wbpogjbyzelmxqeaazu[djdqdlmpfmezzehvjl]qdquppvgjweftqvph[equcifktaceuqwoakk]uxemheczqpboerwq',
'eqeycwhpzzryclb[mvthqzizihyfvtdgon]maeannxtfakrfmg[xlxbqdqlglfspvyqrx]chjokbtqngjjsidqdyf[nnmqygvepumttyp]zipyquwulqtblevg',
'hvvzujphepxjyypzp[isabpxdneywzpzr]rjbcrfhnidqlywbgvxf',
'fcswktnxobrvovrjg[qsaxxwxgrenkdcpfvx]bmivhngglvcwxwgjz',
'ayzzozmdklbhitpd[xwlznwdbvtciozoykoy]ainwvvxkreuvsgdatbm',
'zbhxhhqfeurqurm[buuctguwokorlkfq]extdceaqdkokhdaxzqj',
'arqsuxhcivbxfiuf[jfqqzwkamooqvyj]awbpyjrtunzulggzmh[iipnlkhwzzmzcdi]ktvdnpdmzmkrqavxsxy[dnoqbxknjvouymfz]brcemvbpovqjdvps',
'bmfbcrmibywamwmic[npcluivjtbtwmwxmx]mxyepxnjdabcuiexhwi',
'yywsnxvznbcockrn[fnmwrszfamgerfhocoa]uxfgnvtphthtmeuyy[houdomoboxleqhrf]zznqyqwslypolnqef[ttbcfuirmlnwevhzw]dmohemntzpwivaab',
'paikbyhegnbvcqa[kawvebmxrhzszrncq]noltxgnszsqxfbxbrk',
'yogujlygnpdyhkxpdf[bawcwagtpbuwaorpa]noyoqlkcbsytnzywva[zvdbrjsxhozvyrugdnr]yyehxcwcnepivtjntex',
'rbgkskquxcvswaf[xihgvfvaxkptizohvn]tbntgfbhclvkdael[zuxdeparbafjpwqvg]cpfuexhjmkrdurlbnis[vfmoasavisksmltggm]hsnrpmdkogfxnprmvxu',
'gxuxnshdgyttcjzvk[lsxpwpvsoquxuazidye]mfihmxgxumzfhnm',
'vmqbwehpqesssnps[jkyzwrfofkfqkse]glwxlfrqaamjejrievu[jhbggigitejevdzgqsm]sqxbxgyvfpqtxrlbca',
'qoetptacgfcrdrstl[gpcfptpchpeiicbmfd]vsjqqgbwiqlndgmop',
'cpjplvpmbumvgsduald[sowmjselnjpjwhav]flufpydujtzuzusyrr',
'cmbehdhyvukkufctwpl[toklbggcxvjerfqozbj]wqbacnegquxmszdul[ggzaznwywpswuxmlmg]swowxuqlmlfvxmznm',
'rclnyybawbizurp[cptbsqptpvcuchcyncy]rlqjeblagqogxwy[mwexxfjhkiyoihog]slgmmhvjhpomcvgabu[xgipgcmbydzmayywci]tptdbfqkemdnuzvuz',
'kbaghyebhrmquslcfc[ukdaffinqagmwhvhl]ruyaqrvavvfrzwiyit[jdhkzojqtxymxoaval]qfxsbqwjtsudcet',
'obscoqxaeartfjmeue[dtceaealpasuxsdoo]zhtpbqqfonksrcpu',
'fsjxwoamqjhjvyyr[johjhabbsofojaxccga]tqcnhtvkimixbyiqt',
'zdatmhxwkinjiumoy[qwhfmokowsvzgcngeax]uqebryzrbawakjz[ltilidihghatuhi]lljxtazlhxbrnvwsrc[updgoblisisvpdqngzo]tjvlrlfopjdoyoisim',
'hinhkyqfttbnnou[luuiucbkkrnwiuqbwb]ujfitmunviqwhkiziy[wqbetolmyaceofd]wbwbxudxttgmtuxjeo',
'jgaozdtecqmpueg[bnfjhfyhdndzlkxrcb]esbfjomhfrfvzgm[wqvhdvpvrbsazqzgnw]lkmrymdcupndnoktuv',
'wjzkfwmrsnyjitglauy[jnncpybddtktmehxz]hluaspiawjwywug[ujwjjttoevainaxqmer]gewchllvjclaahplb[haewxwlxjjnfggtg]uxmnawcpzfwhfiefo',
'jogfshkvmshdacro[anluswkewepuhbemk]rwfxbxtmtfgxatwj[lwqompcrkgqzkajgrqg]ckjftivpzkflgbifzx[autylalyokqqlxgu]chewqmwkwewmwoby',
'vhqxmrwadjsfoprv[imclvgvrtvqfbcllpr]kmgvgofdlkarrusoo',
'kwkqhpdsrkdlhuq[njldfvflplvygnihg]hikxtejykexrghupbqz[tanglgtyodyncabh]ennzrvfvgcnlehci',
'zqokauntjcoqolc[kfjplmodgrkaeuuvq]fqicoryxfrkubee[fcncbrofqpyxdnejn]yebngpgxcbjnivisgza[bpwzrwupgpmtbhg]ufxyezblslkscovzaqd',
'udmbexywtscnesd[azofuoboewwundyif]mykxybobvefathvqkfx',
'zrfmusbfbogbrsin[gaayijtuqfbfnxb]cgjsibujnswdmuhfez[rhatyymizrxrqud]wpvajerbhxbtrva',
'badqhtkxeokdbres[wmdthitngyoujdumxfb]lnafdeqakaggcdttnq[acuhhjaemkakovqq]vfvloofttmvvolbpgb',
'ooyljflrcdoujmfajfu[qvnbylveipljcmgrvl]cjfvbounfvjfpsxmbnj[mohdhwcdrykexihcgvb]gfzxjkkqdnspzbqb[jkoiqbqtbjxgezxvsgn]juvveztzrtcxhyp',
'ebfbaesgsxjbwhkmpxp[dzkhyyykwhayaztjt]xkxdjdlfvlzpqbb[tjdqvwygsgoldpffs]uwccbahfnjkhbfzcocf',
'uayfnudukxaldfgdvh[tshkbhbydlzzndsc]wtjmhgayuizllbngcr[tfglywxclqmgpeatsva]riocgxwsethrhbh[xnerbhkafskywvgxbdl]yzubvjedgzbpqqng',
'nticpuumzthsihk[asrmrtlzizgsvnvcxny]wjntjizixwyedcrh',
'yfyzedhbbtpqiwmri[uqxjtkmjcivoqatycbc]etqdfgffuplikkgrug[ezipcwmudtfakrrif]kumvfsiqqyfrbcbvgf[upsfgrzgndzpzxhmx]aewrwjwdquhsagmgwah',
'kupmpwwjcwmmrhum[aakppoytxqucqfncv]gpuyruwkndprpqjqwup[lrcoaodsmpmlhnhnyq]zathwgfvwmumcjwaa',
'fahbkbakvcwwazgioub[ouuvcmqsmykbkhfhj]gntumiippgacbcl',
'ukqzagjymparwzqvw[lnkduutsjulfxuqug]lvupmgsyiquqeepmgsv[ekenewopqmddlcqc]rhnwektxgccickla',
'gfgrgtizxajkaicjcc[mftrzuftzrgrwilsv]uckwgxywnamzjglbnts',
'hzqfveaxrqycvuolynx[ztsmaipixbuhbmv]ebvofyoeponbpip',
'vwwekuavrftztxb[aywyoempmajrdkxpsc]eibnjbszsfsapujqn[rxpcsihuzszefcdzl]gsahdvozzgxjhontxk',
'efuoofbuyjoaqjd[achnmlslfvovmgt]xcuyvikslsewgqlx[gjxolnhgqhhglojjqhy]iarxidejlgphqwaei',
'uxpcurtzqgpgtzkvp[mibqtgwackcedfri]otnnsgolldyzdpbew[tmgiijgjuvjykwahml]xxgjgzmnicxmywdubrb[hwhcgbzhuoankdubft]rxqzywfyuliatahn',
'abbhujqyoaphnruaih[yidrkxgrxeoarph]fvryghhzqrobkbsck[dnokdwmkbktlfoihxl]ttptfiadsswiwsfbvf',
'djwqivpbexyvdquh[qmmdydhjbmunyjixviv]nradabzesdavhasjbjs[lsabjblhocebvyhfee]hwbyvnzltgezasg',
'dxnkgspqhyejogxstsk[jfgckouqypxttst]axtisjbtaviwafh',
'xuabbxdwkutpsogcfea[tgetfqpgstsxrokcemk]cbftstsldgcqbxf[vwjejomptmifhdulc]ejeroshnazbwjjzofbe',
]

describe "the differences between ians list and mine" do
  xit "can do something" do
    my_successful_addresses = my_list.map { |ml| ml[:address] }
    difference = ians_list.reject {|il| my_successful_addresses.include? il }
    p difference.count
  end  

  it "can match one that ian did" do
    input = 'lcototgbpkkoxhsg[erticxnxcjwypnunco]notoouvtmgqcfdupe[hubcmesmprktstzyae]unuquevgbpxqnrib[egalxegqwowylkdjkdg]spqmkzfjnzwcwgutl'

    candidate = IPV7.hypernet_sequences({address: input})
    expect(candidate[:hypernet_sequences]).to match_array [
      'erticxnxcjwypnunco',
      'hubcmesmprktstzyae',
      'egalxegqwowylkdjkdg',
    ]

    candidate = IPV7.supernet_sequences(input)
    expect(candidate[:supernet_sequences]).to eq 'lcototgbpkkoxhsgnotoouvtmgqcfdupeunuquevgbpxqnribspqmkzfjnzwcwgutl'

    r = IPV7.supports_ssl? input
    expect(r[:supports_ssl]).to eq true
  end
end
















